# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"D\n\x0e\x41\x64\x64UserRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"1\n\x0f\x41\x64\x64UserResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"E\n\x0f\x41uthUserRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"6\n\x10\x41uthUserResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0bserver_time\x18\x02 \x01(\t23\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x32p\n\x0bUserService\x12.\n\x07\x41\x64\x64User\x12\x0f.AddUserRequest\x1a\x10.AddUserResponse\"\x00\x12\x31\n\x08\x41uthUser\x12\x10.AuthUserRequest\x1a\x11.AuthUserResponse\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_ADDUSERREQUEST = DESCRIPTOR.message_types_by_name['AddUserRequest']
_ADDUSERRESPONSE = DESCRIPTOR.message_types_by_name['AddUserResponse']
_AUTHUSERREQUEST = DESCRIPTOR.message_types_by_name['AuthUserRequest']
_AUTHUSERRESPONSE = DESCRIPTOR.message_types_by_name['AuthUserResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

AddUserRequest = _reflection.GeneratedProtocolMessageType('AddUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERREQUEST,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:AddUserRequest)
  })
_sym_db.RegisterMessage(AddUserRequest)

AddUserResponse = _reflection.GeneratedProtocolMessageType('AddUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERRESPONSE,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:AddUserResponse)
  })
_sym_db.RegisterMessage(AddUserResponse)

AuthUserRequest = _reflection.GeneratedProtocolMessageType('AuthUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHUSERREQUEST,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:AuthUserRequest)
  })
_sym_db.RegisterMessage(AuthUserRequest)

AuthUserResponse = _reflection.GeneratedProtocolMessageType('AuthUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHUSERRESPONSE,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:AuthUserResponse)
  })
_sym_db.RegisterMessage(AuthUserResponse)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=18
  _HELLOREQUEST._serialized_end=46
  _HELLOREPLY._serialized_start=48
  _HELLOREPLY._serialized_end=77
  _ADDUSERREQUEST._serialized_start=79
  _ADDUSERREQUEST._serialized_end=147
  _ADDUSERRESPONSE._serialized_start=149
  _ADDUSERRESPONSE._serialized_end=198
  _AUTHUSERREQUEST._serialized_start=200
  _AUTHUSERREQUEST._serialized_end=269
  _AUTHUSERRESPONSE._serialized_start=271
  _AUTHUSERRESPONSE._serialized_end=325
  _GREETER._serialized_start=327
  _GREETER._serialized_end=378
  _USERSERVICE._serialized_start=380
  _USERSERVICE._serialized_end=492
# @@protoc_insertion_point(module_scope)
